### ISSUE TITLE
Clarify role of ODEState object

### ISSUE THREAD

**Issue by aarchiba** [drhagen/scipy_ode#1]
Each ODE solver class is accompanied by an ODE state object. What is this object for? I can see two functions it could serve:

1. It stores all the state the ODE solver needs to continue integration from this point onwards, or

2. It stores all the state necessary for dense evaluation within this step.

If the answer is 1, what is stored in the solver object? Isn't that the natural place for the solver state? What is gained by having an external state object? It allows one to resume solving at an earlier point, I suppose.

If the answer is 2, then state objects can be used for dense evaluation even in solvers where the dense evaluation is not just evaluating a polynomial (if any exist): solver objects would have an evaluate function that takes a state object. If we're content with polynomials, then it's not clear what an external state object is for.

**Comment by drhagen** [comment]
It is both. However, the state required to advance to the next step is larger than the state required to provide a dense solution. For example, `step_size` and `J` are needed to advance the solver, but not to densely sample the solution. All of the state that is needed to densely sample the solution is stored on a single field `state` so that integrators like `solve_ivp` can grab and store it for dense evaluation later without having to know what fields need to be saved for each particular solver.

The external state object definitely does not allow for resuming at an earlier point. There is other important state lost that is required to advance the solver from that point.

**Comment by aarchiba** [comment]
I'm thinking about how to do this for the Bulirsch-Stoer code; in this case the cleanest solution is probably to store the derivatives at start end and middle, which are what is used to construct the Hermite polynomial. But why not simply provide that polynomial if the user wants it?

**Comment by aarchiba** [comment]
Just to clarify: a state object associated with a step, right, not an end point? What should the initial state object (before a step has been taken) contain?

**Comment by drhagen** [comment]
> I'm thinking about how to do this for the Bulirsch-Stoer code; in this case the cleanest solution is probably to store the derivatives at start end and middle

Have you looked at how `RungeKutta45` does it? It has to store middle points. The first step has None for its middle points and then each step stores the middle points from the step it just took.

> But why not simply provide that polynomial if the user wants it?

What aspect of this feature is not covered by `solver.spline`?

> Just to clarify: a state object associated with a step, right, not an end point? What should the initial state object (before a step has been taken) contain?

The state is changed by each step. The initial state object contains the initial state, usually `t=t0` and `y=y0` plus `f=f0` for solvers that need that. The state object should contain the minimize information from each step to reconstruct the solution with `spline`.
