### ISSUE TITLE
Discussion of the base class and the design in general

### ISSUE THREAD

**Issue by nmayorov** [drhagen/scipy_ode#16]
Do you really believe than the base class (as it is now) makes writing new solvers easier (including user solvers)? Also objectively the current base class does nothing except introducing some abstractions (I'm not saying that it is never useful).

I have an impression that implementing a new solver is always a special problem and you are better not to be restricted by any abstractions, interfaces to follow, etc. What really matters is the final result (basically arrays with numbers / solution functions to call). Also consider that we don't know how to put multistep methods in such design and whether it will be possible.

My point is that maybe OOP hierarchy is not useful for writing a set of different solvers. Instead maybe it's better to write solvers separately (by whatever way is the most convenient), but assure that they all return consistent outputs. Basically it is the current design of `solve_ivp`, but we can use a class for more flexibility (including single stepping). 

Generally I think we focus on wrong things now and don't progress. I feel it is more fruitful to focus on specific solvers isolated, rather than trying to create some universal abstractions which *might be* useful. As for the idea of allowing users writing their own solvers --- I suggest to abandon it. Mainly because I strongly doubt it will give any benefits compared to just writing the code from scratch.

**Comment by aarchiba** [comment]
The key thing this design does is specify the interface a solver object should provide so that the convenience functions can call any solver, whether included in scipy or provided by the user. There are also possibilities for putting code into the solver base class to simplify writing solvers: the check_input function is a start, but I think it also makes sense to do array reshaping there, so that solvers only have to deal with one-dimensional state, but users can use n-dimensional input arrays. 

As for what to focus on, the interface to solver objects is key. But if you want to start writing new solvers, or porting the code to cython, go ahead.

**Comment by drhagen** [comment]
> Do you really believe than the base class (as it is now) makes writing new solvers easier (including user solvers)? Also objectively the current base class does nothing except introducing some abstractions (I'm not saying that it is never useful).

You are correct that in Python the abstract base class is never strictly needed. Right now, there is some functionality provided, but not a lot. If we deleted the abstract base class after copying the redundant functionality into each solver, we would still to need to have a well-defined interface and document it somewhere. I like having a base class as the place to do this, but I am open to alternative designs.

> I have an impression that implementing a new solver is always a special problem and you are better not to be restricted by any abstractions, interfaces to follow, etc. What really matters is the final result (basically arrays with numbers / solution functions to call). 

This is a good point. A common interface for all ODE solvers may not exist. I suspect that there is. I feel like all IVP solvers can fit into a paradigm of stepping from one state to another and providing a way to interpolate those states. I am willing to be proven wrong. There may be a lot of ODE solver out there that operate differently.

> Also consider that we don't know how to put multistep methods in such design and whether it will be possible.

It is possible to implement multistep methods in the current design (#14 possibility 1) . I am just looking for a more elegant solution.

> My point is that maybe OOP hierarchy is not useful for writing a set of different solvers. Instead maybe it's better to write solvers separately (by whatever way is the most convenient), but assure that they all return consistent outputs. Basically it is the current design of `solve_ivp`, but we can use a class for more flexibility (including single stepping).

Could you provide a design for this? It sounds like you want to copy the body of `solve_ivp` into a method of each solver class. But if the solver class has stepping, I am not sure what this method would provide that one could not already obtain with the current `solve_ivp` integrator that factors out the common code. I'll admit that this could have an impact on Cythonizing the main integration loop, but I'd like to see what that impact is.

> Generally I think we focus on wrong things now and don't progress.

I actually thought we were close to being done with just a few more details to be worked out.

> I feel it is more fruitful to focus on specific solvers isolated, rather than trying to create some universal abstractions which might be useful.

I am also opposed to creating abstractions that _might_ be useful. I withdrew the discontinuities proposal (#11) when it looked like there was no universally good way to handle them. But the step solver interface has already proven itself to be very useful to me; I have used it to write a special integrator for a project I am working on.

**Comment by nmayorov** [comment]
I feel that I was not constructive enough and I'm sorry for that. 

I guess I mainly express my preferences of the workflow: just implement everything step-by-step separately, then see if there is a common functionality and refactor a bit. It can be called a bottom-up approach and I think it is a good one for relatively small packages, especially in Python. It also means relying on simplest data structures (numpy arrays mainly), which can be considered as an advantage as well. I mainly rely on my experience during GSoC when I worked on `least_squares` --- I followed this approach and it worked well, but theoretically I could start developing "general lsq optimizer", etc, etc. (but I believe it would be a terrible idea in that case). 

But for ODE this stage can be considered as done (the loops for RK and Radau methods), but it would be useful to have a multistep method before generalizing.

> Could you provide a design for this? It sounds like you want to copy the body of solve_ivp into a method of each solver class.

The design would be to have a single `IVPSolver` class with a `method` keyword. The interpretation is that there is a single ODE solver, but it has many options (including `method`). Code reuse and different behavior depending on `method` can be achieved by different means. 

But now it seems to me that this is a rather unnatural and bad approach. So I have to agree that for a class interface (solver with state and `step` method)  we should use an inheritance (or just implement each class separately). 

-----------

So after all I agree that the base class and inheritance is the way to go. I'll try to think about specifics better.

---------

> I actually thought we were close to being done with just a few more details to be worked out.

What are the goals? I was thinking:

1. Finish class structure.
2. Add a multistep method (partially just to find out how to fit it in).
3. Cythonize.

**Comment by drhagen** [comment]
> 1. Finish class structure.

> 2. Add a multistep method (partially just to find out how to fit it in).

I updated #14. I think that's the biggest issue left with the classes and it affects multistep methods.

**Comment by nmayorov** [comment]
Hi,

I created a wiki page with a class design proposal: https://github.com/nmayorov/scipy_ode/wiki/Design-of-OdeSolver Sure it is not very polished and misses some details.

It does some things differently than what you currently have. Most notable I don't introduce anything like `OdeState` or `OdeSolution`. Everything is managed inside the class and outputs are simple arrays or floats. I personally like this approach better (provided it can be implemented in a sensible way).

If you are interested you can move it to the wiki in this repo and uncheck "Restrict editing to collaborators only" in settings. I would like to see your commentary.

**Comment by drhagen** [comment]
> If you are interested you can move it to the wiki in this repo and uncheck "Restrict editing to collaborators only" in settings. I would like to see your commentary.

I have [copied your design to this repository](https://github.com/drhagen/scipy_ode/wiki/Design-of-OdeSolver) and made the wiki editable.

**Comment by drhagen** [comment]
I have a few thoughts. This is fairly similar to the options 5 and 6 from #14. Your design provides a few additional features.

### variable `max_step`
The main purpose of `max_step` in an ODE solver is to prevent variable step solvers from stepping over sudden, short-lived features in the RHS, like a narrow pulse in the middle of a flat plain. I think it may be it's only purpose. Please let me know if there are others.

If you know where this pulse will be, it is more efficient to have variable `max_step` (like in your design) so that the integration is not slowed on the flat part. This could be incorporated into the current design. When the important points are known, I think they are sometimes implemented as some sort of `important_points` argument; most solvers forcibly stop on the points, but others may merely ensure that their error estimates are consistent with the RHS value at that point. If the important points are not known beforehand, then `max_step` is needed as a backup.

### `t_crit`
I understand your desire to not have both `t_crit` and `max_step`. I think your plan is to require whatever is called `step` to supply `max_step` as `t_crit - t`. However, I don't think `t_crit` can be removed because there is no floating point guarantee that `t + (t_crit - t) == t_crit`, and `t_crit` can be very sensitive to floating point errors. One alternative is to provide `t_crit` to `step` rather than `max_step`. Users may supply a different value of `t_crit` on each step to simulate a `max_step`.

I guess my opinion is that I like to have everything needed to define a solution specified in the constructor (e.g. `max_step`, `important_points`) and `step` just gives the user a chunk of it. There is a nice separation of concerns there.

### `integrate`
Does the internal state stop at `t` or does it step until it passes `t`? In any case, this method would be on the base class because it's the same for all solvers, right?

I am not entirely opposed to this method. It seems to provide redundant capabilities to `step` and `spline`. I guess I prefer this functionality in a convenience function because it provides such specific capabilities on top the solvers. I guess I want to provide the minimum capabilities on the class solvers needed to define the solver itself. Everything you do with the solver is written in a convenience function.

### events as part of solver
With the current design, the user of the solver chooses how to do event handling. With the new design, the solver chooses. I can conceive of situations where that might be useful (perhaps there are solvers that unusually long steps or can handle wiggles better), but I guess I think of events as something that is done to the solution of an ODE rather than something intrinsic to the ODE solver itself. If you needed a special event handler, I would expect it to be because of a special event rather than because of a special solver.

### convenience functions
In your design, does `solve_ivp` go away?

### `store` flag
I am not a fan of flags in general. Some methods work depending on the value of this flag. The `spline` function is also redundant with the return value of `step`. One could trivially reconstruct it by saving all the step splines. In your design, can a user change `store` later to start storing the states?

**Comment by nmayorov** [comment]
Thank you for the feedback! 

## variable `max_step`

I believe there is another reason to have `max_step`. If a step is happen to be too large, then higher order terms in Taylor expansion might be more significant than the term we based our step selection strategy, then a solver will continue to select large steps and the accuracy of the solution will degrade. I don't think there is an automatic way to spot such situation, but a user can adjust `max_step` if he finds the returned solution suspicious. I did it once when solving a stiff problem with `radau` solver --- the resulting spline was not monotonous as expected at some regions, I could fix it by reducing the `max_step`.

Providing `max_step` option to `step` method goes well with the idea to give maximum control to users who want it.

As for `important_points` --- sounds like a good idea too, but I think it's optional. If you want to add it at some point --- go ahead. Also how about merging it with `t_crit`? It looks logical to me: there can be several critical points and we want the solver to stop at each of them.

### `t_crit`

If you believe `t_crit` is necessary not only to specify integration direction, then I don't mind to have it (also see the previous point with `t_crit` containing multiple values).

> I guess my opinion is that I like to have everything needed to define a solution specified in the constructor (e.g. max_step, important_points) and step just gives the user a chunk of it. There is a nice separation of concerns there.

I think a good design might be to provide `max_step` in the constructor, but the argument in `step` will overwrite it (for one step) if provided. 

### `integrate`

> Does the internal state stop at t or does it step until it passes t?

My idea was that it stops, i.e. we want to integrate to exactly `t`. This is a usual approach in most function-based solvers, right?

> In any case, this method would be on the base class because it's the same for all solvers, right?

Hopefully it can be put in the base class for all methods. But if some method needs its own implementation --- we can override it.

> I guess I prefer this functionality in a convenience function because it provides such specific capabilities on top the solvers.

To be honest this is what I don't get. If we started with an object-oriented design, then we should stick to it, in my opinion. When some solver will require a different integration routine, then handling this in a convenience function might be considered as a bad design, whereas overriding it in the class is a standard solution.

### events as part of solver

In theory I mostly agree with what you said. But I suspect that vast majority of users will think of it as if scipy ODE solver doest't have event detection capabilities and will want to use MATLAB instead.

Also bundled event detection allows conveniently define and use terminal events.

As for our method being "imperfect":

1. I'm sure people will happy to use this imperfect method anyway. It is a popular feature in MATLAB I believe (and it is implemented the same conceptually).
2. It is a good method in most cases. The very advanced user (like @aarchiba for example), can use stepping interface and hopefully achieve what they want.

### `store` flag

> I am not a fan of flags in general. Some methods work depending on the value of this flag.

I understand you point, it's not very clean design when used in classes. But I find it logical in this case nevertheless. It asks a user how he wants to use the solver:

1. `'spline` Compute continuous solution --- the most convenient way, but can be prohibited by memory limitations.
2. `'state'`  Continuous solution is not necessary, but he still wants to see the solution curve. I feel that this case is marginal and can be removed perhaps.
3. `'none'` A user knows at which points he wants to evaluate the solution and wants to save memory.

> One could trivially reconstruct it by saving all the step splines.

My concern that this is really inconvenient and will be avoided by most of the users. And it forces to use `step` method.

> In your design, can a user change store later to start storing the states?

I think this is not necessary.

--------------

## Relation between `step` and `integrate`.  

My thinking is that `step` method is the method most of users will never want to use. But it is available for advanced applications nevertheless. And `integrate` method should be as convenient as possible and provide commonly used features in a straightforward manner (very similar to the original `solve_ivp`). 

-------------

OK, hopefully we will be able to extract useful ideas from this again lengthy discussion.

**Comment by drhagen** [comment]
### `t_crit` and `max_step`

> I believe there is another reason to have `max_step`. If a step is happen to be too large, then higher order terms in Taylor expansion might be more significant than the term we based our step selection strategy, then a solver will continue to select large steps and the accuracy of the solution will degrade. I don't think there is an automatic way to spot such situation, but a user can adjust max_step if he finds the returned solution suspicious. I did it once when solving a stiff problem with radau solver --- the resulting spline was not monotonous as expected at some regions, I could fix it by reducing the max_step.

I feel like this kind of thing is the responsibility of the solver. For a good solver, changing `max_step` should be less efficient than changing `rtol`. We have to trust that the solver should be ensuring that each step and the interpolator obeys the tolerance the user requested, right?

I guess it doesn't really matter. We both agree that `max_step` needs to exist. If users set `max_step` for some other reason, that is their prerogative.

> Providing `max_step` option to step method goes well with the idea to give maximum control to users who want it.

I am all for maximum control, but I am hesitant to put features into the API for all solvers that will have no meaning for some solvers. For example, all fixed step-size solvers have no concept of `max_step`, yet they would still be required to accept this parameter.

### `integrate`

> My idea was that it stops, i.e. we want to integrate to exactly t. This is a usual approach in most function-based solvers, right?

With function-based solvers, the solver is not guaranteed to left in a state that integration can resume from that point. Your design implies that it is. What effect does this have on the adaptive step size? If there is a only a tiny step left to take, after completing the tiny step, does the solver (1) take the next step with the previously safe step size or (2) set the step size to the tiny step and adaptively ramp up from there or (3) rewind to the last normal step and continue past the previous termination. We could probably come up with sensible answers, but we would have to carefully study any solver added because I don't think (1) or (2) are well-defined operations on all solvers. This isn't a case that is usually covered in the literature, I think.

> > I guess I prefer this functionality in a convenience function because it provides such specific capabilities on top the solvers.

> To be honest this is what I don't get. If we started with an object-oriented design, then we should stick to it, in my opinion. When some solver will require a different integration routine, then handling this in a convenience function might be considered as a bad design, whereas overriding it in the class is a standard solution.

I like the functional interface better interface for normal use. This is familiar syntax: `sol = solve_ivp(my_fun, y0, 0, 10)`. I think it is your sentiment that the object-oriented solvers are not that user-friendly. If that is your sentiment, then I completely agree. I think they need to exist solely for extensibility: to make it possible for advanced users to do new things with the solvers and to add new solvers themselves (advanced users here also applies to Scipy devs contributing new functionality).

I guess I also believe that if we adopt one of the options in #14 there will never need to be a solver-specific integration scheme.

### `events`

> In theory I mostly agree with what you said. But I suspect that vast majority of users will think of it as if scipy ODE solver doest't have event detection capabilities and will want to use MATLAB instead.

I completely agree. We need event detection in Scipy ODE. Your implementation is what attracted me to this project in the first place. What I meant was that event handling should be part of the convenience function (because it works directly on the solution, not caring which solver created it), rather than part of the solver object. In the future, we could add additional options to `solve_ivp` to tweak the event handling, or someone could write their own convenience function that did event handling differently. And all that could be done without touching a single solver.

> > One could trivially reconstruct it by saving all the step splines.

> My concern that this is really inconvenient and will be avoided by most of the users. And it forces to use step method.

I agree. At this point, I did not realize that the convenience functions were not part of your design.

-----

> OK, hopefully we will be able to extract useful ideas from this again lengthy discussion.

Yes, I think this has been very helpful. I am going to make a condensed version of my design on the wiki, so we have that for comparison rather than just the code.

**Comment by aarchiba** [comment]
`max_step`: independently of solution quality, a user might provide a `max_step` option as a way to make sure that an event was not missed. Specifically, the obvious way to do event detection is to evaluate the event functions at the end of each step, and when an event function changes sign within a step, a root-finder is run to locate the event. But event functions may not be monotonic, and big steps might jump right over a pair of sign changes. So `max_step` would allow a user to still use the convenience function but still ensure that events were not missed, in some cases. (In others the minimum spacing between sign changes can be arbitrarily small and the user will need to supply their own cleverness.)

`t_crit`: this is to ensure that the solver doesn't try to integrate past points that are known problems. Such points might be okay as the end/beginning of a step, or they might require jiggery-pokery (changing the value of a step function parameter).

Object-oriented interface versus convenience functions: I would say that convenience functions need only provide those features that are widely-used and easy to describe. If we provide a good selection of ODE solvers, it's very rare that people will need to implement their own (but of course we should make it possible). But there are a large number of more-complicated use cases that are just not really sensible to cram into a convenience function: 
* The user might want to retry integrating past or to a problem area with different solver parameters (higher number of maximum iterations, smaller minimum step size, relaxed tolerance, additional points in `t_crit`, or some other thing we haven't thought of). 
* The user might need to stop and switch coordinate systems.
* The user might need more-clever event detection that takes advantage of the ability to compute derivatives or the polynomial nature of the dense output to locate all events.
* The user might be doing some kind of ongoing calculation with a high-dimensional solution, so that even saving the solution values at all desired output points is inefficient.
* The user might want some more complex kind of root-finding - for example, they want to evaluate the solution $Y(t)$ at all times $t_i$ where some auxiliary function $f(Y(t_i), t_i) = f_i$.
* The user might not know ahead of time where the solution needs to be evaluated - it might depend on user input, for example (say plotting the solution in a system where the user can pan and zoom arbitrarily). 
The idea of an ODE solver as a stateful object that you can advance as needed is a fairly standard interface, whether it is object-oriented or not. 

Once again I encourage you to take a look at the features provided by well-established FORTRAN codes; obviously their interfaces are clumsy, but the features they provide have been needed by users over the years.

**Comment by drhagen** [comment]
I added to the wiki the design of [convenience functions plus step-return-spline](https://github.com/drhagen/scipy_ode/wiki/David's-Design). I thought it would be good to have a place to store the basic interface as a point of reference.

**Comment by drhagen** [comment]
> But there are a large number of more-complicated use cases that are just not really sensible to cram into a convenience function:

Could you expand on what you are arguing for? I agree that none of this belongs in the built-in convenience functions. But every item your list seems like an argument for a step solver interface, for which I don't think there is any disagreement that it should exist.

**Comment by aarchiba** [comment]
> > But there are a large number of more-complicated use cases that are just not really sensible to cram into a convenience function:

> Could you expand on what you are arguing for? I agree that none of this belongs in the built-in convenience functions. But every item your list seems like an argument for a step solver interface, for which I don't think there is any disagreement that it should exist.

I guess I am arguing that the single-stepping interface is also user-facing, it's just designed for users with more complicated needs. In terms of code, I agree, it's pretty much what we have agreed on, and the main questions are precisely what the interface should look like:
* Is it worth putting some kind of event detection code in the solver object or is that only needed for the convenience functions?
* Should it do shape conversion on `y`? That is, allowing solvers to work with 1D vectors but users to see arbitrary-shape ndarrays.
* Should it make a dense-output object available only as the return value from `step` or upon request (e.g. from a `solution` method)?
* How modifiable should it be - `maxstep`, `maxcalls`, `atol`/`rtol`, the RHS function, other things the user might want to change partway through integration? What is lost by forcing the user to construct a fresh solver object to continue (say using a stiff solver)?
* How should it handle exceptions and invalid values from the RHS?
* How should integration errors of various sorts be handled? What needs to be done to resume after an error? Is there a systematic way for users to detect what kind of problem stopped the integration? (RHS domain error, `minstep` limit hit, `maxcalls` limit hit, solver internal failure, ...)
* Do we want to support fixed-step-size solvers? (in particular symplectic solvers can't really be made adaptive in the same way)
* Do we want to support solvers with more elaborate RHS requirements? (second-order solvers, geometric solvers that treat positions and momenta differently, ...)
* Do we want to support changing the dimension of `y` partway through integration? (changes in discretization, for example, or n-body solvers with collisions or escapes)

There's also the question of the interface to dense-output objects:
* Can we safely assume they're always polynomials? Can we always use one of the objects from `scipy.interpolate` or do some require other implementations (e.g. based on orthogonal polynomial expansions) for numerical stability?
* What to call single-step dense output objects? `spline` is wrong here, since it's a single polynomial not defined by global conditions.
* What functionality should they provide? Derivatives, antiderivatives, polynomial-specific root-finding, extrapolation? 
* What interface should they provide? `__call__`? `derivative` method returning a particular derivative? `derivatives` method returning all derivatives, or all up to some order? `t0` `t1` and `order` attributes?

The convenience functions, some of them anyway, will return a solution object containing many such pieces, and many of the same interface questions arise. We should also try to match interfaces in `scipy.interpolate`, but of course they don't particularly match each other.

**Comment by aarchiba** [comment]
Specifically, I think it's not a good idea to have `step` return the dense output object for that step. Users may not have any points within the step where they want to evaluate the solution, and constructing the dense output objects can cost extra computation. I'd rather have the dense output object available upon request from the solver.

**Comment by nmayorov** [comment]
As far as I figured the design proposed by David:

1. Solvers implemented as classes with a `step` method and nothing more.
2. The main user interface is `solve_ivp`.

I can see it as a good compromise. The only think I _strongly_ don't like is that all options are hidden in `**options`, because:

1. It is not very convenient if you want to use these options.
2. Much worse that it will promote unthinking usage with default options. And to be honest this is what I wanted to be different in new solvers. I want users have access to all necessary information right here and make intelligent choices based on that.

I know that this is how it's done in `optimize.minimize`, but I think it can be done better in this case, because:

1. We don't rely on wrapping existing codes. New solvers can emerged, but focusing on a core set and interface is more important in my opinion.
2. Unlikely we will have that many methods.
3. Maybe `optimize.minimize` is not the best way in the first place.

OK, I again started to promote the idea of "monolithic" design, but it has so many advantages in my opinion. Need to put stepping interface into it somehow.

**Comment by drhagen** [comment]
> The only think I strongly don't like is that all options are hidden in **options

[In the current code](https://github.com/drhagen/scipy_ode/blob/ode/scipy_ode/ivp.py#L71-L100), all the options used by the built in solvers and their defaults are listed in the doc string for `solve_ivp`. I think that is a good design if you do. There is no harm in having good, easy-to-find documentation on the user-facing functions. I truncated that section in the wiki to keep it short.

**Comment by nmayorov** [comment]
It looks quite good then. But I wonder if we can move more options to the main part, like `rtol` and `atol` are very universal. 

When I was trying to think it through again I had thoughts like this:

1. To expose options more clearly perhaps `solve_ivp` can accept an already initialized solver?
2. No, this idea is weird, better to implement`solve_ivp` as a class method then.

So I returned to the questions: "Wouldn't it be better to have a class interface?" Then the workflow for a user will be like:

1. Scan the `scipy.integrate` page where classes are briefly annotated (or a tutorial on ODE integration).
2. Pick the one he thinks is suitable for the problem.
3. Carefully study its documentation, initialize and run. Or if it doesn't suite --- check other methods.

I think it is a quite solid and "well defined" scheme. Whereas if we have `solve_ivp` as a function with options depending on a solver --- it is less so in my opinion: switching between class and `solve_ivp` docs, not fully universal way to list all relative options in `solve_ivp`.

Sorry if I bored you with this idea, but can we discuss it one more time? That is "Wouldn't it be better to have a class interface?"

**Comment by drhagen** [comment]
>  Sorry if I bored you with this idea, but can we discuss it one more time? That is "Wouldn't it be better to have a class interface?"

I am not bored at all. It is important that we get this right because it will be very difficult to change later. I don't want this to become the third not-quite-perfect ODE solver suite in Scipy. I understand the desire to have only one interface. It should require good justification to argue against your plan to simplify the number of interfaces by 50%. However, it is still my opinion that having two interfaces is better, so let me try to provide that justification. If I were to guess, I would say 60% of users will want the solution at discrete times, 30% of users will want an evaluatable solution between two times, and 10% will want something more advanced that they can build themselves with a step solver.

I want to maximally optimize for the 90% case. I think the 90% case is best handled by a couple of convenience functions with an interface similar to the ones provided by Matlab's `ode*`, Scipy's `integrate.odeint`, Mathematica's `NDSolve`, Julia's ODE.jl, etc. I don't want to copy an interface just because it is familiar. Some of these languages don't have classes, so of course they use a function. But I honestly believe this is the optimal interface: a function that takes a RHS, some initial conditions, and either a final time or a list of times and returns the solution. If we have `integrate` be a method rather than a function, then we can't provide a default solver. (Not huge deal, Julia and Matlab don't have a default.) If we have `integrate` be a method, then users have to first supply RHS and initial conditions to the constructor and then supply the final time or list of times to the method. (Again, not a huge deal, but a little bit of friction for what should be the 90% use case.) If we have `integrate` be a method, new users will have a more exposure to the step solving capabilities than I would like. Users have to call the constructor before `integrate`, so they'll have to think about what to provide for `store`. They'll be calling `integrate`, which I would expect to be documented in the same place as `step` and `spline` and all the state attributes. Maybe we want users to run into our cool step solver functionality, but I think I would rather keep the advanced features in a separate interface.

**Comment by nmayorov** [comment]
As I understand you are saying that the functional interface is more natural and straightforward in typical cases. I think it's fair.

But I think it is worth to consider a class interface. It can happen that scipy will introduce this new way and it will turn out to be more convenient and flexible. One advantage I see in a class interface that it will allow for explorative approach: integrate to some point, check the result and do something with it, then continue integration if necessary (using `integrate` or `step` as appropriate).

So I suggest: 

1. Go with function interface as the main road. Here we need to figure the best way to document it. You mentioned Mathematica's NDSolve --- the current docs in this repository conceptually looks the same. So I guess it's a valid approach to hide options as `**options` but document them, although I would still consider to listing them explicitly (even though some are irrelevant for some solvers) and leave `**options` for the very exotic options (only relevant for potential new options).
 2. I can try to experiment with class interface and see how it feels. In the ideal case scenario we can ask people to vote on scipy-dev mailing list (when both versions will be ready).

----------------

One note about the current design of functions. I personally would try to put all options into a single function `solve_ivp` instead of separating them by output types. At least it would be my default approach. It's just a conventional approach in scipy and Python in general, because Python language is suitable for that. From users' perspective --- having one entry point is more convenient than several. 

I think `OdeSolution` might have different fields defines or left as None depending on the solution type we want. Callable part might be an attribute (like `sol`) as well

`LazyOdeSolution` --- another thing, I think it needs more considerations how it should be implemented and whether to include it. I saw the PR by @aarchiba --- the one shortcoming I noticed is that it is not vectorized, which I think really contradicts the way people used to work with scipy/numpy.

------------------

Good that you brought Julia and Mathematica ODE suites. I would say that we are already on par with ODE.jl and NDSolve additionally provides multistep Adams (explicit, non-stiff, aka ode113) and BDF (implicit, stiff, aka ode15s).

I started to study BDF method and I think I'm on the right track now, but still need to figure out a lot of important details. I'll try to start writing the code, iterating from rough (and buggy) to detailed and refined versions, I hope it will work out. When we'll have a multi-step method we can figure out how to fit it into the package.

**Comment by drhagen** [comment]
> I can try to experiment with class interface and see how it feels. In the ideal case scenario we can ask people to vote on scipy-dev mailing list (when both versions will be ready).

I think this is a good way of going about it given that both designs have merit.

> One note about the current design of functions. I personally would try to put all options into a single function solve_ivp instead of separating them by output types. At least it would be my default approach. It's just a conventional approach in scipy and Python in general, because Python language is suitable for that. From users' perspective --- having one entry point is more convenient than several.

There are several reasons I prefer several functions over one. We have different solvers be an keyword argument of the function because they take similar inputs and have the same output, even though they do very different things internally. For the convenience functions, the situation is reversed; they do essentially the same thing internally, but their inputs and outputs are different. And different types of inputs and outputs is a pretty good reason to have a separate function. If we ever want to add functionality, we can simply add another function, not make the existing function super complicated.

**Comment by aarchiba** [comment]
> LazyOdeSolution --- another thing, I think it needs more considerations how it should be implemented and whether to include it. I saw the PR by @aarchiba --- the one shortcoming I noticed is that it is not vectorized, which I think really contradicts the way people used to work with scipy/numpy.

I haven't vectorized it yet because we are still discussing whether it should exist at all. Of course if we include it it should be as vectorized as any numpy ufunc; this will most naturally be done by rewriting it in cython, as we plan to do for all the functions we are discussing here.

> There are several reasons I prefer several functions over one. We have different solvers be an keyword argument of the function because they take similar inputs and have the same output, even though they do very different things internally. For the convenience functions, the situation is reversed; they do essentially the same thing internally, but their inputs and outputs are different. And different types of inputs and outputs is a pretty good reason to have a separate function. If we ever want to add functionality, we can simply add another function, not make the existing function super complicated.

I agree, and I'd point out that a general design principle is, return types should not depend on input values. The function name should make it clear what type of object is being returned: an array of values, or a solution object.

I'm not sure there's any point having both the lazy and non-lazy versions; if the lazy version is worth including, what's the point of adding the same function returning the same object except that it raises exceptions for some values?

**Comment by nmayorov** [comment]
> > There are several reasons I prefer several functions over one. We have different solvers be an keyword argument of the function because they take similar inputs and have the same output, even though they do very different things internally. For the convenience functions, the situation is reversed; they do essentially the same thing internally, but their inputs and outputs are different. And different types of inputs and outputs is a pretty good reason to have a separate function. If we ever want to add functionality, we can simply add another function, not make the existing function super complicated.

> I agree, and I'd point out that a general design principle is, return types should not depend on input values. The function name should make it clear what type of object is being returned: an array of values, or a solution object.

OK, I'm fine with it.

**Comment by aarchiba** [comment]
I should note that I've been adding to the design document at [https://github.com/drhagen/scipy_ode/wiki/David's-Design], both to propose alternatives and to flesh out some of the details.
